### ISSUE TITLE
Is there a way to get the old version of Shakify called "Camera Wobble"?

### ISSUE THREAD

**Issue by VHSvince** [EatTheFuture/camera_shakify#12]
I am just gonna assume that "Camera Wobble" is an earlier version of Shakify
and Im wondering if anyone has a download for it since it has stuff the new
Shakify doesnt have anymore. (Walking 2D, which I would love to have)
I'm not expecting anyone to still have it but it would really help me out. 
Thanks!

Here, a screenshot of someone who used it.
![image](https://user-images.githubusercontent.com/55703238/191802545-4ad1b747-c6bc-45e9-8ebe-22aaf26f4a1f.png)

**Comment by cessen** [comment]
> I am just gonna assume that "Camera Wobble" is an earlier version of Shakify

That is correct.

> (Walking 2D, which I would love to have)

We removed that because (from our perspective, at least) it's redundant with the full 3D walk that's already there.  For us, 2D is just what we settle for when we can't get a 3D track of a shake for some reason.  So I'm curious what your use case is where you specifically want a 2D version of a camera shake.

**Comment by VHSvince** [comment]
Yes, understandable. I respect that.
Do you mean the 'Walk to the store' shake with 3D Walk?
Because I see a big difference in that one and Walking 2D.
Walking 2D has that nice Y rotation, that bobbing and you can really feel the steps of the cameraman.
I know.. very picky but yeah. 
Just asking if its possible to get somehow.
Thanks for answering so quickly.

**Comment by cessen** [comment]
Ah, got it.

It looks like the commit where we removed that (and some other shakes) was d2a8e2c6b97297d0938c295ff5ae38542581fc46.  The commit just before that was 5f3923339f508445e6c3b0eb873e2ebafdf095c8, so I think if you download that, it should do the trick.  In case you're not familiar with Github, here's a direct download link: https://github.com/EatTheFuture/camera_shakify/archive/5f3923339f508445e6c3b0eb873e2ebafdf095c8.zip

However, there have been bug fixes and feature additions since then, so I can't guarantee that this older version of the addon will work.  If it doesn't, you can try copying `shake_data.py` from this older version over to the newest version.  I *think* the format is still the same, so it should (probably?) work.

Let me know if any of this works for you or not!

**Comment by VHSvince** [comment]
Ahh!
Copying over `shake_data.py` made it work!
Amazing.
Thank you alot for doing all that for me!

**Comment by cessen** [comment]
Awesome!  Glad I could help!
