### ISSUE TITLE
Feature Request - Add new/custom shake profiles.

### ISSUE THREAD

**Issue by DickJokez69** [EatTheFuture/camera_shakify#22]
Hey! I love the addon, but I really wish there were a way to add custom shake profiles to the addon. Either via motion tracked data, baked keyframes, etc. There's a lot of good profiles already there, but I'd love to be able to use this to call up some custom or user-submitted profiles.

**Comment by cessen** [comment]
We're not planning to add this to Camera Shakify.  The purpose is to quickly toss convincing camera shake onto a camera.  If you want to do something more custom, that's what Blender's general animation tools are for.

Having said that, if there are specific kinds of shake that you feel are lacking, we'd love that feedback!

**Comment by DickJokez69** [comment]
That's a shame.
"quickly toss convincing camera shake onto a camera"
This was exactly _why_ I asked about custom profiles in the first place. The speed this addon offers really lends itself to the workflow you've described. Compared to clicking a profile in your addon, and appending existing cameras that have already existing tracking info (either with the asset browser or appending usually), the addon really is the way to go. I'm not even talking about using the addon to create tracks or anything like that, just some way of creating profiles similar to the ones already on offer in the shake_data.py file.

The addon feels like it could be a great library for camera shakes, rather than just a selection of presets.
Hell, even an example workflow of how you did it yourself would be welcome (assuming you didn't just code them in by hand). It doesn't seem that hard to just add them myself into the existing shake_data.py file

**Comment by cessen** [comment]
Maybe I'm misunderstanding what you're asking for.  What I thought you were asking for was a way to import completely new shake data.  But I'm now wondering if you meant something else by "custom profile".  For example, if you already specified a mix of camera shakes in the addon, being able to save that as a kind of preset?

**Comment by DickJokez69** [comment]
I just mean being able to create new shakes _from scratch_ similar to how they're already implemented in the addon.
I'm not sure how you went about creating the data used in the existing presets, but let's say you made them by keyframing a camera, and did some magic to distill it into the data used in the shake_data.py. I'd like to be able to do the same.
So I could whip up a shake I like via keyframes, do _whatever it is you do to turn it into usable data for the addon_, and have it as a nifty preset I could call up the same way as the default ones.

The ultimate end goal, being I could take some handheld videos with my phone or camera, track it, bake to keyframes, turn it into usable data for the addon, and be able to call up those shots for different projects.
_All of this assuming you're keyframing/animating cameras_. I don't know if that's what you did to make the data for the presets, but it's just a hypothetical.

Like I said, even if it's not really a feature you're interested in implementing, a quick rundown of how you made the default presets should be enough of a jumping off point I think to just manually put my own in via the shake_data.py file (I think).

**Comment by cessen** [comment]
Okay, in that case I did understand you correctly the first time.

What you're asking for in some sense is like an addon system for an addon.  Maybe there's a simple way to do that for Camera Shakify, but it's not really the intended use case for it, and not something we want to maintain, answer support questions for, etc.  It seems like it would be a big time sink in the long run, for fairly little benefit.

`shake_data.py` is pretty straightforward: for each shake you have a name, a frame rate, and a list of keyframes for each transform channel.  So it should be pretty straightforward to extend yourself if you want to, just following the same format as the existing shakes.

But this also brings me back to my question from earlier: what kinds of shakes do you feel are missing from the addon right now, such that you feel the need to extend it in the first place?  Assuming they're in scope, I think it would make more sense to just add those to the core addon so that everyone can benefit.

**Comment by DickJokez69** [comment]
Ah I see, so it really is as simple as taking the transforms of the camera for the keyframes and inputting them in sequence into the data? I don't know much about scripting, but I think I _should_ be able to write a script to get that info to put in.
So just to get this right. Say you had 4 keyframes at 30fps, for a new preset, you just specify what framerate it's at, and write down the xyz location for the 1st keyframe (specifying what frame the key is on), then do the same for the other 3? Adding xyz rotation if it's also there?

As for what shakes are missing, I'd really just like more shots that you'd see from chase vehicles shooting another. What's there is decent for handheld shots, and the "Bike on gravel" one does alright to get that noise, but there's not really anything that really captures that essence of a camera attached to a vehicle. Like don't get me wrong, I can get close enough with what's there with mixing things, but I just feel like I'm missing some subtle things that I cant quite get with what's there.

Hence the plan of making a few of my own presets to mix in. I figured they were kinda specific to my use and wouldn't be of much benefit to anyone else that wasn't looking for that sort of thing, and asking you to track some shots with a camera attached to your car just for me didn't seem like the best use of your time.

**Comment by cessen** [comment]
Yeah, that's how to do it.  Also, there's Python code in the addon for exporting just the keyframe data to the right format, if you want to use that as a starting point:

https://github.com/EatTheFuture/camera_shakify/blob/c17881e3c384da1ec4f9e13d4b6bebf0b1428276/action_utils.py#L24-L41

> but there's not really anything that really captures that essence of a camera attached to a vehicle.

Ah, that makes sense.  We do have "Out Car Window", but that's a handheld camera inside a moving vehicle, rather than the high-frequency shake you get from one that's attached.

> and asking you to track some shots with a camera attached to your car just for me didn't seem like the best use of your time.

We're also open to contributions, as long as they're in-scope, licensed as CC0, and are filling a gap.  In scope basically means:

1. Continuous looping shakes, not a sudden event like an explosion.
2. Actually captured from real camera motion, not hand animated or generated.

So if you want to strap a camera to your own vehicle and turn the resulting shake into a loop, we'd be happy to include it if it turns out well.  Ideally we want the loops to be 10 seconds or longer, so that loops aren't super obvious—but that's not always necessary, depending on the nature of the shake.

Incidentally, something I think we could have done better with the existing shakes is using a higher frame rate for shakes with high frequencies.  So if you do want to contribute, I'd say shoot at 60 fps just in case.  We can always downsample on our side afterwards if it turns out it wasn't needed.
