### ISSUE TITLE
Cant fucking install

### ISSUE THREAD

**Issue by jrdbn** [EatTheFuture/camera_shakify#26]
When i try to install it,
 it doesnt work and the tutorial is fucking useless
![image](https://github.com/EatTheFuture/camera_shakify/assets/168861728/ee94c38a-f5a2-413f-aa1c-f0a6a3ca13a2)
**i have tried installing every one of these and nothing fucking happens**

**Comment by nosipitan** [comment]
Here - https://youtu.be/yHYKxBOG6LE?si=0x1mepbaihuzsk4m
Make sure your in blender 3 or above.






(Stop swearing Dude)

**Comment by zilverboi** [comment]
the video never showed how you specifically install the mod, and he's probably swearing because he is as frustrated as me. i won't swear for now

**Comment by nosipitan** [comment]
https://youtu.be/LzdoUTvAgXk?si=QjG3VaH5HFSg7t0e&t=65

**Comment by cessen** [comment]
As the video @nosipitan linked to explains, when you're installing an addon for Blender (unless it's literally just a single .py file), you want to directly install from the zip file without extracting it.  This is true of all Blender addons, not just Camera Shakify, because it's how Blender works.

I agree that the [Blender manual](https://docs.blender.org/manual/en/latest/editors/preferences/addons.html) could be clearer about this.
