### ISSUE TITLE
Bake camera Data to keyframes

### ISSUE THREAD

**Issue by Tiefseetauchner** [EatTheFuture/camera_shakify#5]
Hi!
I just tried to render smtg with Crowdrender and realized it (understandably the way it's implemented) doesn't transfer the constraint data
Can we implement a Bake to Keyframes option? I don't know how it'd work, as I don't have any experience with yeeting Driver data into Keyframes, but it sounds like a really useful feature for cloud rendering that might not (or probably doesn't) have the addon installed

Best, Lena :)

**Comment by cessen** [comment]
Ah!  Thanks for the heads up on this.

Yeah, that's definitely a good idea.  Is this something you need urgently (e.g. you're delivering to a client?).

**Comment by Tiefseetauchner** [comment]
Nah, I don't need it urgently, just smtg I noticed and thought would be useful, workaround is to install the addon on all the computers I render on, thanks for the question tho 👍🏻

**Comment by cessen** [comment]
Okay, thanks!  I'll just add it to my to-do list, then.

**Comment by cessen** [comment]
It looks like Blender's standard animation baking feature works just fine for this, so I don't think we need to implement it as a feature in Camera Shakify itself.

The steps to so the animation baking (e.g. in preparation for sending to a render farm) are:

1. Select the camera.
2. Select the menu item `Object -> Animation -> Bake Action...`
3. Make sure to enable the `Visual Keying` check box (otherwise it won't work).
4. Click the `OK` button to perform the bake.
5. Remove all the shakes from the camera's Camera Shakify list.

Hope this helps!

**Comment by Tiefseetauchner** [comment]
Oh thank you, didn't know you can bake it like that, that does help! I will think about if it makes sense to implement it as a feature in the addon, as well as how implementation would work and whether there might be a better way to implement it than just calling the Blender function, as it might allow for more flexibility if you bake the Data right from the Addon Storage
I'd consider adding at least a button to call it, as someone like me might not know the way and have the same issue again...
