### ISSUE TITLE
Keyframing strength from 0 to 1 then back down from 1 to 0 does does not return original camera orientation

### ISSUE THREAD

**Issue by tmaniscalco90** [EatTheFuture/camera_shakify#9]
Keyframing strength from 0 to 1 then back down from 1 to 0 does does not return original camera orientation for looping.

**Comment by cessen** [comment]
It's not totally clear to me what the issue is here.  The strength doesn't have anything to do with timing, so I'm not sure why you would expect it to cause the animation to loop back.

(Also, the camera shakes already loop automatically anyway, so trying to manually loop them shouldn't be necessary.)

But maybe I'm misunderstanding something?

**Comment by cessen** [comment]
Upon re-reading this, I think I perhaps did misunderstand you.

When you say 'strength', I assume you mean the 'influence' parameter?  In that case, yes, setting the influence to zero should effectively disable the camera shake, and therefore result in the same camera position (assuming the camera is not otherwise animated).  If it is not behaving that way, then indeed it is a bug.

However, I can't reproduce your issue on either of my systems.  Can you provide a .blend file that demonstrates the problem?

**Comment by cessen** [comment]
Closing due to lack of response from the reporter. If anyone else runs into this issue and can provide additional information, please feel free to re-open or create a new issue.
